"""GeoTask Core v1.0 — Canonical Intermediate Representation and tooling.

v1.0 represents a clean break from the v0.x prototype. The canonical IR
(ir.py) is the single source of truth for Parser, Validator, Executor,
and Result Builder.
"""

from geotask_core.v1.ir import (
    GeotaskVersion,
    GeotaskMetadata,
    SpaceCRS,
    SpaceDefinition,
    GeoObject,
    OperatorContract,
    Assertion,
    Task,
    ExecutionStep,
    ExecutionDefinition,
    VerificationDefinition,
    OutputContract,
    CanonicalDocument,
)
from geotask_core.v1.result import (
    GEOTASK_RESULT_SCHEMA_ID,
    GEOTASK_RESULT_SCHEMA_VERSION,
    CheckResult,
    ExecutionSummary,
    ResultSummary,
    OverallResult,
    GeotaskResult,
)
from geotask_core.v1.extension_profiles import (
    CONTROL_PROFILE_ID,
    CONTROL_PROFILE_VERSION,
    validate_extension_profiles,
)
from geotask_core.v1.control_expressions import (
    CONTROL_EXPRESSION_LANGUAGE_ID,
    CONTROL_EXPRESSION_LANGUAGE_VERSION,
    ExpressionSyntaxError,
    ExpressionEvaluationError,
    parse_control_expression,
    evaluate_control_expression,
    referenced_identifiers,
)
from geotask_core.v1.control_evaluation import (
    CONTROL_EVALUATION_SCHEMA_ID,
    CONTROL_EVALUATION_SCHEMA_VERSION,
    ControlContextError,
    ControlEvaluationFormatError,
    ControlContextEntry,
    ControlContext,
    ControlBlockEvaluation,
    ControlEvaluationResult,
    build_control_context,
    evaluate_control_profile,
    load_control_evaluation,
)
from geotask_core.v1.serialized_validation import (
    VersionedPayloadContract,
    VersionedPayloadValidationReport,
    invalid_versioned_payload_report,
    validate_versioned_payload,
    EXECUTION_RESULT_VALIDATION_CONTRACT,
    CONTROL_EVALUATION_VALIDATION_CONTRACT,
)
from geotask_core.v1.artifact_registry import (
    ARTIFACT_REGISTRY_SCHEMA_ID,
    ARTIFACT_REGISTRY_VERSION,
    GEOTASK_DOCUMENT_SCHEMA_ID,
    GEOTASK_DOCUMENT_SCHEMA_VERSION,
    ARTIFACT_VALIDATION_SCHEMA_ID,
    ARTIFACT_VALIDATION_SCHEMA_VERSION,
    ArtifactDescriptor,
    list_artifact_descriptors,
    get_artifact_descriptor,
    artifact_registry_payload,
)
from geotask_core.v1.schema_bundle import (
    SCHEMA_BUNDLE_VERSION,
    SCHEMA_BUNDLE_MANIFEST_FILENAME,
    BUNDLED_SCHEMA_IDS,
    list_bundled_schema_ids,
    schema_bundle_manifest,
    load_bundled_schema,
    load_artifact_schema,
    verify_schema_bundle,
)
from geotask_core.v1.artifact_validation import (
    ARTIFACT_VALIDATION_REPORT_VERSION,
    ArtifactValidationFormatError,
    ArtifactValidationReport,
    load_artifact_validation_report,
    validate_artifact_payload,
    validate_artifact_file,
)

__all__ = [
    "GeotaskVersion",
    "GeotaskMetadata",
    "SpaceCRS",
    "SpaceDefinition",
    "GeoObject",
    "OperatorContract",
    "Assertion",
    "Task",
    "ExecutionStep",
    "ExecutionDefinition",
    "VerificationDefinition",
    "OutputContract",
    "CanonicalDocument",
    "GEOTASK_RESULT_SCHEMA_ID",
    "GEOTASK_RESULT_SCHEMA_VERSION",
    "CheckResult",
    "ExecutionSummary",
    "ResultSummary",
    "OverallResult",
    "GeotaskResult",
    "CONTROL_PROFILE_ID",
    "CONTROL_PROFILE_VERSION",
    "validate_extension_profiles",
    "CONTROL_EXPRESSION_LANGUAGE_ID",
    "CONTROL_EXPRESSION_LANGUAGE_VERSION",
    "ExpressionSyntaxError",
    "ExpressionEvaluationError",
    "parse_control_expression",
    "evaluate_control_expression",
    "referenced_identifiers",
    "CONTROL_EVALUATION_SCHEMA_ID",
    "CONTROL_EVALUATION_SCHEMA_VERSION",
    "ControlContextError",
    "ControlEvaluationFormatError",
    "ControlContextEntry",
    "ControlContext",
    "ControlBlockEvaluation",
    "ControlEvaluationResult",
    "build_control_context",
    "evaluate_control_profile",
    "load_control_evaluation",
    "VersionedPayloadContract",
    "VersionedPayloadValidationReport",
    "invalid_versioned_payload_report",
    "validate_versioned_payload",
    "EXECUTION_RESULT_VALIDATION_CONTRACT",
    "CONTROL_EVALUATION_VALIDATION_CONTRACT",
    "ARTIFACT_REGISTRY_SCHEMA_ID",
    "ARTIFACT_REGISTRY_VERSION",
    "GEOTASK_DOCUMENT_SCHEMA_ID",
    "GEOTASK_DOCUMENT_SCHEMA_VERSION",
    "ARTIFACT_VALIDATION_SCHEMA_ID",
    "ARTIFACT_VALIDATION_SCHEMA_VERSION",
    "ArtifactDescriptor",
    "list_artifact_descriptors",
    "get_artifact_descriptor",
    "artifact_registry_payload",
    "SCHEMA_BUNDLE_VERSION",
    "SCHEMA_BUNDLE_MANIFEST_FILENAME",
    "BUNDLED_SCHEMA_IDS",
    "list_bundled_schema_ids",
    "schema_bundle_manifest",
    "load_bundled_schema",
    "load_artifact_schema",
    "verify_schema_bundle",
    "ARTIFACT_VALIDATION_REPORT_VERSION",
    "ArtifactValidationFormatError",
    "ArtifactValidationReport",
    "load_artifact_validation_report",
    "validate_artifact_payload",
    "validate_artifact_file",
]
