"""GeoTask Core: Lightweight spatial task representation for LLMs.

STIR was the original prototype name. The project has been renamed to GeoTask.
Selected old function names, the ``stir`` CLI, and the ``stir:`` YAML key
remain deprecated aliases. The old ``stir_core`` Python package path is not
distributed; imports must use ``geotask_core``.

v1.0 modules are available under geotask_core.v1.*
"""

from geotask_core._version import __version__

from geotask_core.models import (
    PointObject,
    LineObject,
    RectObject,
    PolygonObject,
    MultiPolylineObject,
    StirDocument,
)
from geotask_core.parser import (
    load_geotask, validate_geotask, load_stir, validate_stir,
)
from geotask_core.ops import (
    distance_2d,
    line_intersects_rect,
    multi_polyline_intersects_rect,
    point_in_polygon,
)
from geotask_core.runner import run_geotask, run_stir
from geotask_core.normalizer import normalize_model_output
from geotask_core.evaluator import evaluate_model_output
from geotask_core.verifier import verify_normalized_result
from geotask_core.result_schema import (
    STATUS_VERIFIED,
    STATUS_CONTRADICTED,
    STATUS_NEED_REVIEW,
    STATUS_EXTRACTED,
)

# v1.0 exports
from geotask_core.v1.enums import (
    ExecutionMode, VerificationMode, AssuranceLevel,
    ExecutionStatus, ClaimStatus, EncodingType,
    is_valid_geotask_id,
)
from geotask_core.v1.ir import CanonicalDocument, GeotaskMetadata
from geotask_core.v1.canonicalizer import canonicalize
from geotask_core.v1.validator import validate_canonical
from geotask_core.v1.executor import execute_canonical
from geotask_core.v1.result import (
    GEOTASK_RESULT_SCHEMA_ID,
    GEOTASK_RESULT_SCHEMA_VERSION,
    GeotaskResult,
)
from geotask_core.v1.extension_profiles import (
    CONTROL_PROFILE_ID,
    CONTROL_PROFILE_VERSION,
    validate_extension_profiles,
)
from geotask_core.v1.control_expressions import (
    CONTROL_EXPRESSION_LANGUAGE_ID,
    CONTROL_EXPRESSION_LANGUAGE_VERSION,
    ExpressionSyntaxError,
    ExpressionEvaluationError,
    parse_control_expression,
    evaluate_control_expression,
    referenced_identifiers,
)
from geotask_core.v1.control_evaluation import (
    CONTROL_EVALUATION_SCHEMA_ID,
    CONTROL_EVALUATION_SCHEMA_VERSION,
    ControlContextError,
    ControlEvaluationFormatError,
    ControlContextEntry,
    ControlContext,
    ControlBlockEvaluation,
    ControlEvaluationResult,
    build_control_context,
    evaluate_control_profile,
    load_control_evaluation,
)
from geotask_core.v1.core_benchmark import (
    CORE_BENCHMARK_ID,
    CORE_BENCHMARK_REPORT_VERSION,
    CORE_BENCHMARK_SCHEMA_ID,
    CORE_BENCHMARK_SCHEMA_VERSION,
    CORE_BENCHMARK_VERSION,
    CoreBenchmarkFormatError,
    DEFAULT_BENCHMARK_ITERATIONS,
    DEFAULT_BENCHMARK_WARMUP_ITERATIONS,
    DEFAULT_MAX_PIPELINE_P95_MS,
    load_core_benchmark_report,
    run_core_benchmark,
)
from geotask_core.v1.serialized_validation import (
    VersionedPayloadContract,
    VersionedPayloadValidationReport,
    invalid_versioned_payload_report,
    validate_versioned_payload,
    EXECUTION_RESULT_VALIDATION_CONTRACT,
    CONTROL_EVALUATION_VALIDATION_CONTRACT,
)
from geotask_core.v1.artifact_registry import (
    ARTIFACT_REGISTRY_SCHEMA_ID,
    ARTIFACT_REGISTRY_VERSION,
    GEOTASK_DOCUMENT_SCHEMA_ID,
    GEOTASK_DOCUMENT_SCHEMA_VERSION,
    ARTIFACT_VALIDATION_SCHEMA_ID,
    ARTIFACT_VALIDATION_SCHEMA_VERSION,
    ArtifactDescriptor,
    list_artifact_descriptors,
    get_artifact_descriptor,
    artifact_registry_payload,
)
from geotask_core.v1.schema_bundle import (
    SCHEMA_BUNDLE_VERSION,
    SCHEMA_BUNDLE_MANIFEST_FILENAME,
    BUNDLED_SCHEMA_IDS,
    list_bundled_schema_ids,
    schema_bundle_manifest,
    load_bundled_schema,
    load_artifact_schema,
    verify_schema_bundle,
)
from geotask_core.v1.artifact_validation import (
    ARTIFACT_VALIDATION_REPORT_VERSION,
    ArtifactValidationFormatError,
    ArtifactValidationReport,
    load_artifact_validation_report,
    validate_artifact_payload,
    validate_artifact_file,
)
from geotask_core.v1.agent_artifacts import (
    AGENT_EVIDENCE_RECOVERY_SCHEMA_ID,
    AGENT_EVIDENCE_RECOVERY_SCHEMA_VERSION,
    AGENT_GENERATION_PREPARATION_SCHEMA_ID,
    AGENT_GENERATION_PREPARATION_SCHEMA_VERSION,
    AGENT_REVISION_RETRY_SCHEMA_ID,
    AGENT_REVISION_RETRY_SCHEMA_VERSION,
    AGENT_REVISION_VERIFICATION_SCHEMA_ID,
    AGENT_REVISION_VERIFICATION_SCHEMA_VERSION,
    AgentArtifactFormatError,
    load_agent_evidence_recovery_report,
    load_agent_generation_preparation_report,
    load_agent_revision_retry_report,
    load_agent_revision_verification_report,
)
from geotask_core.v1.agent_integration import (
    AGENT_INTEGRATION_PROFILE_ID,
    AGENT_INTEGRATION_PROFILE_VERSION,
    AGENT_INTEGRATION_REPORT_VERSION,
    AgentIntegrationError,
    AgentToolDescriptor,
    EvidenceRecoveryResult,
    list_agent_tool_descriptors,
    agent_integration_profile_payload,
    recover_evidence_request,
)
from geotask_core.v1.agent_generation import (
    AGENT_GENERATION_REPORT_VERSION,
    AGENT_REVISION_REQUEST_VERSION,
    AGENT_REVISION_VERIFICATION_VERSION,
    AGENT_REVISION_RETRY_VERSION,
    AgentGenerationError,
    DocumentRepairAction,
    GeneratedDocumentPreparationResult,
    GeneratedDocumentRevisionItem,
    GeneratedDocumentRevisionVerificationResult,
    GeneratedDocumentRevisionRetryResult,
    build_generated_document_revision_request,
    verify_generated_document_revision,
    retry_generated_document,
    prepare_generated_document,
)
from geotask_core.v1.runtime_interface import (
    RUNTIME_INTERFACE_PROFILE_ID,
    RUNTIME_INTERFACE_PROFILE_VERSION,
    RUNTIME_DESCRIPTOR_SCHEMA_ID,
    RUNTIME_REQUEST_SCHEMA_ID,
    RUNTIME_RESPONSE_SCHEMA_ID,
    RUNTIME_DESCRIPTOR_SCHEMA_VERSION,
    RUNTIME_REQUEST_SCHEMA_VERSION,
    RUNTIME_RESPONSE_SCHEMA_VERSION,
    RUNTIME_DESCRIPTOR_ARTIFACT_ID,
    RUNTIME_REQUEST_ARTIFACT_ID,
    RUNTIME_RESPONSE_ARTIFACT_ID,
    VALIDATE_ARTIFACT_OPERATION_ID,
    EXECUTE_NONLOCAL_OPERATION_ID,
    RESOLVE_EVIDENCE_OPERATION_ID,
    EXECUTE_ACTION_OPERATION_ID,
    REFERENCE_RUNTIME_ID,
    REFERENCE_RUNTIME_VERSION,
    RuntimeInterfaceFormatError,
    RuntimeArtifact,
    RuntimeDiagnostic,
    RuntimeOperationDescriptor,
    RuntimeDescriptor,
    RuntimeRequest,
    RuntimeResponse,
    RuntimeAdapter,
    load_runtime_descriptor,
    load_runtime_request,
    load_runtime_response,
    validate_runtime_request_contract,
    validate_runtime_response_contract,
    reference_runtime_descriptor,
    runtime_interface_profile_payload,
    FailClosedMockRuntime,
    submit_runtime_request,
)

__all__ = [
    "__version__",
    "PointObject",
    "LineObject",
    "RectObject",
    "PolygonObject",
    "MultiPolylineObject",
    "StirDocument",
    "load_geotask",
    "validate_geotask",
    "load_stir",
    "validate_stir",
    "distance_2d",
    "line_intersects_rect",
    "multi_polyline_intersects_rect",
    "point_in_polygon",
    "run_geotask",
    "run_stir",
    "normalize_model_output",
    "evaluate_model_output",
    "verify_normalized_result",
    "STATUS_VERIFIED",
    "STATUS_CONTRADICTED",
    "STATUS_NEED_REVIEW",
    "STATUS_EXTRACTED",
    # v1.0
    "ExecutionMode",
    "VerificationMode",
    "AssuranceLevel",
    "ExecutionStatus",
    "ClaimStatus",
    "EncodingType",
    "is_valid_geotask_id",
    "CanonicalDocument",
    "GeotaskMetadata",
    "canonicalize",
    "validate_canonical",
    "execute_canonical",
    "GEOTASK_RESULT_SCHEMA_ID",
    "GEOTASK_RESULT_SCHEMA_VERSION",
    "GeotaskResult",
    "CONTROL_PROFILE_ID",
    "CONTROL_PROFILE_VERSION",
    "validate_extension_profiles",
    "CONTROL_EXPRESSION_LANGUAGE_ID",
    "CONTROL_EXPRESSION_LANGUAGE_VERSION",
    "ExpressionSyntaxError",
    "ExpressionEvaluationError",
    "parse_control_expression",
    "evaluate_control_expression",
    "referenced_identifiers",
    "CONTROL_EVALUATION_SCHEMA_ID",
    "CONTROL_EVALUATION_SCHEMA_VERSION",
    "ControlContextError",
    "ControlEvaluationFormatError",
    "ControlContextEntry",
    "ControlContext",
    "ControlBlockEvaluation",
    "ControlEvaluationResult",
    "build_control_context",
    "evaluate_control_profile",
    "load_control_evaluation",
    "CORE_BENCHMARK_ID",
    "CORE_BENCHMARK_REPORT_VERSION",
    "CORE_BENCHMARK_SCHEMA_ID",
    "CORE_BENCHMARK_SCHEMA_VERSION",
    "CORE_BENCHMARK_VERSION",
    "CoreBenchmarkFormatError",
    "DEFAULT_BENCHMARK_ITERATIONS",
    "DEFAULT_BENCHMARK_WARMUP_ITERATIONS",
    "DEFAULT_MAX_PIPELINE_P95_MS",
    "load_core_benchmark_report",
    "run_core_benchmark",
    "VersionedPayloadContract",
    "VersionedPayloadValidationReport",
    "invalid_versioned_payload_report",
    "validate_versioned_payload",
    "EXECUTION_RESULT_VALIDATION_CONTRACT",
    "CONTROL_EVALUATION_VALIDATION_CONTRACT",
    "ARTIFACT_REGISTRY_SCHEMA_ID",
    "ARTIFACT_REGISTRY_VERSION",
    "GEOTASK_DOCUMENT_SCHEMA_ID",
    "GEOTASK_DOCUMENT_SCHEMA_VERSION",
    "ARTIFACT_VALIDATION_SCHEMA_ID",
    "ARTIFACT_VALIDATION_SCHEMA_VERSION",
    "ArtifactDescriptor",
    "list_artifact_descriptors",
    "get_artifact_descriptor",
    "artifact_registry_payload",
    "SCHEMA_BUNDLE_VERSION",
    "SCHEMA_BUNDLE_MANIFEST_FILENAME",
    "BUNDLED_SCHEMA_IDS",
    "list_bundled_schema_ids",
    "schema_bundle_manifest",
    "load_bundled_schema",
    "load_artifact_schema",
    "verify_schema_bundle",
    "ARTIFACT_VALIDATION_REPORT_VERSION",
    "ArtifactValidationFormatError",
    "ArtifactValidationReport",
    "load_artifact_validation_report",
    "validate_artifact_payload",
    "validate_artifact_file",
    "AGENT_GENERATION_PREPARATION_SCHEMA_ID",
    "AGENT_GENERATION_PREPARATION_SCHEMA_VERSION",
    "AGENT_REVISION_VERIFICATION_SCHEMA_ID",
    "AGENT_REVISION_VERIFICATION_SCHEMA_VERSION",
    "AGENT_REVISION_RETRY_SCHEMA_ID",
    "AGENT_REVISION_RETRY_SCHEMA_VERSION",
    "AGENT_EVIDENCE_RECOVERY_SCHEMA_ID",
    "AGENT_EVIDENCE_RECOVERY_SCHEMA_VERSION",
    "AgentArtifactFormatError",
    "load_agent_generation_preparation_report",
    "load_agent_revision_verification_report",
    "load_agent_revision_retry_report",
    "load_agent_evidence_recovery_report",
    "AGENT_INTEGRATION_PROFILE_ID",
    "AGENT_INTEGRATION_PROFILE_VERSION",
    "AGENT_INTEGRATION_REPORT_VERSION",
    "AgentIntegrationError",
    "AgentToolDescriptor",
    "EvidenceRecoveryResult",
    "list_agent_tool_descriptors",
    "agent_integration_profile_payload",
    "recover_evidence_request",
    "AGENT_GENERATION_REPORT_VERSION",
    "AGENT_REVISION_REQUEST_VERSION",
    "AGENT_REVISION_VERIFICATION_VERSION",
    "AGENT_REVISION_RETRY_VERSION",
    "AgentGenerationError",
    "DocumentRepairAction",
    "GeneratedDocumentPreparationResult",
    "GeneratedDocumentRevisionItem",
    "GeneratedDocumentRevisionVerificationResult",
    "GeneratedDocumentRevisionRetryResult",
    "build_generated_document_revision_request",
    "verify_generated_document_revision",
    "retry_generated_document",
    "prepare_generated_document",
    "RUNTIME_INTERFACE_PROFILE_ID",
    "RUNTIME_INTERFACE_PROFILE_VERSION",
    "RUNTIME_DESCRIPTOR_SCHEMA_ID",
    "RUNTIME_REQUEST_SCHEMA_ID",
    "RUNTIME_RESPONSE_SCHEMA_ID",
    "RUNTIME_DESCRIPTOR_SCHEMA_VERSION",
    "RUNTIME_REQUEST_SCHEMA_VERSION",
    "RUNTIME_RESPONSE_SCHEMA_VERSION",
    "RUNTIME_DESCRIPTOR_ARTIFACT_ID",
    "RUNTIME_REQUEST_ARTIFACT_ID",
    "RUNTIME_RESPONSE_ARTIFACT_ID",
    "VALIDATE_ARTIFACT_OPERATION_ID",
    "EXECUTE_NONLOCAL_OPERATION_ID",
    "RESOLVE_EVIDENCE_OPERATION_ID",
    "EXECUTE_ACTION_OPERATION_ID",
    "REFERENCE_RUNTIME_ID",
    "REFERENCE_RUNTIME_VERSION",
    "RuntimeInterfaceFormatError",
    "RuntimeArtifact",
    "RuntimeDiagnostic",
    "RuntimeOperationDescriptor",
    "RuntimeDescriptor",
    "RuntimeRequest",
    "RuntimeResponse",
    "RuntimeAdapter",
    "load_runtime_descriptor",
    "load_runtime_request",
    "load_runtime_response",
    "validate_runtime_request_contract",
    "validate_runtime_response_contract",
    "reference_runtime_descriptor",
    "runtime_interface_profile_payload",
    "FailClosedMockRuntime",
    "submit_runtime_request",
]
