#!/usr/bin/env python3
"""Verify that a staged GeoTask Core commit does not absorb Integration-owned paths.

This is a local pre-commit ownership gate. It does not stage, commit, tag, push, or
publish anything. The gate inspects only the staged index by default.

Exit codes:
    0: staged paths are acceptable for a Core/governance commit
    1: staged paths cross an explicit ownership boundary
    2: nothing is staged, so no commit scope exists to verify yet
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


FORBIDDEN_CORE_COMMIT_PATTERNS = (
    "examples/integrations/**",
    "tests/test_lowa_gt_*.py",
    "docs/reference/lowa-gt-shadow-study-protocol-v0.1.md",
    "docs/internal/lowa-gt-*",
    "docs/reports/lowa_gt_*",
    ".ai-bridge/**",
    ".codexpro-src/**",
)

ALLOWED_CROSS_LINE_GOVERNANCE_PATHS = (
    "docs/reference/lowa-gt-integration-contract-v0.1.md",
    "docs/reference/cross-line-promotion-gate-v0.1.md",
    "docs/reference/core-distribution-boundary-v0.1.md",
)


def _staged_paths(root: Path) -> tuple[list[str], str]:
    try:
        result = subprocess.run(
            ["git", "-c", "core.quotepath=false", "diff", "--cached", "--name-only"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        return [], f"cannot inspect staged paths: {exc}"
    paths = sorted(line.strip().replace("\\", "/") for line in result.stdout.splitlines() if line.strip())
    return paths, ""


def _head_commit(root: Path) -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def _staged_sha256(root: Path, path: str) -> str:
    result = subprocess.run(
        ["git", "show", f":{path}"],
        cwd=root,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        return "<deleted>"
    return hashlib.sha256(result.stdout).hexdigest()


def _load_baseline_plan(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))["core_baseline_plan"]
    if payload.get("generated_by") != ".release/plan_core_baseline.py":
        raise ValueError("baseline plan was not generated by .release/plan_core_baseline.py")
    if payload.get("state") != "passed" or payload.get("ready_to_stage") is not True:
        raise ValueError("baseline plan is not in a passing ready-to-stage state")
    entries = payload.get("core_paths")
    if not isinstance(entries, list) or not entries:
        raise ValueError("baseline plan has no Core paths")
    for entry in entries:
        if not isinstance(entry, dict) or not entry.get("path") or not entry.get("worktree_sha256"):
            raise ValueError("baseline plan Core paths must include path and worktree_sha256")
    return payload


def _matches(path: str, pattern: str) -> bool:
    return fnmatch.fnmatch(path, pattern)


def verify_core_commit_scope(root: Path, baseline_plan: Path | None = None) -> dict[str, Any]:
    root = root.resolve()
    paths, error = _staged_paths(root)
    if error:
        return {
            "core_commit_scope": {
                "state": "failed",
                "valid": False,
                "staged_count": 0,
                "staged_paths": [],
                "forbidden_paths": [],
                "error": error,
                "side_effects": {"index_changed": False, "commit_created": False, "push_performed": False},
            }
        }

    if not paths:
        return {
            "core_commit_scope": {
                "state": "pending",
                "valid": False,
                "staged_count": 0,
                "staged_paths": [],
                "forbidden_paths": [],
                "allowed_cross_line_governance_paths": list(ALLOWED_CROSS_LINE_GOVERNANCE_PATHS),
                "error": "nothing is staged",
                "side_effects": {"index_changed": False, "commit_created": False, "push_performed": False},
            }
        }

    forbidden: list[dict[str, str]] = []
    for path in paths:
        if path in ALLOWED_CROSS_LINE_GOVERNANCE_PATHS:
            continue
        for pattern in FORBIDDEN_CORE_COMMIT_PATTERNS:
            if _matches(path, pattern):
                forbidden.append({"path": path, "pattern": pattern})
                break

    plan_report: dict[str, Any] | None = None
    plan_failed = False
    if baseline_plan is not None:
        plan_path = baseline_plan if baseline_plan.is_absolute() else root / baseline_plan
        try:
            plan = _load_baseline_plan(plan_path)
            expected_hashes = {
                str(entry["path"]): str(entry["worktree_sha256"])
                for entry in plan["core_paths"]
            }
            expected_paths = sorted(expected_hashes)
            current_head = _head_commit(root)
            missing_paths = sorted(set(expected_paths) - set(paths))
            unexpected_paths = sorted(set(paths) - set(expected_paths))
            content_mismatches = []
            for path in sorted(set(paths) & set(expected_paths)):
                staged_sha256 = _staged_sha256(root, path)
                if staged_sha256 != expected_hashes[path]:
                    content_mismatches.append(
                        {
                            "path": path,
                            "expected_sha256": expected_hashes[path],
                            "staged_sha256": staged_sha256,
                        }
                    )
            head_matches = bool(current_head) and current_head == plan.get("head_commit")
            plan_failed = bool(missing_paths or unexpected_paths or content_mismatches or not head_matches)
            plan_report = {
                "path": str(plan_path),
                "plan_digest": plan.get("plan_digest"),
                "expected_head_commit": plan.get("head_commit"),
                "current_head_commit": current_head,
                "head_matches": head_matches,
                "expected_staged_count": len(expected_paths),
                "missing_paths": missing_paths,
                "unexpected_paths": unexpected_paths,
                "content_mismatches": content_mismatches,
                "exact_staged_plan_match": not plan_failed,
            }
        except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as exc:
            plan_failed = True
            plan_report = {
                "path": str(plan_path),
                "exact_staged_plan_match": False,
                "error": str(exc),
            }

    state = "failed" if forbidden or plan_failed else "passed"
    return {
        "core_commit_scope": {
            "state": state,
            "valid": not forbidden and not plan_failed,
            "staged_count": len(paths),
            "staged_paths": paths,
            "forbidden_paths": forbidden,
            "allowed_cross_line_governance_paths": list(ALLOWED_CROSS_LINE_GOVERNANCE_PATHS),
            "forbidden_patterns": list(FORBIDDEN_CORE_COMMIT_PATTERNS),
            "baseline_plan": plan_report,
            "invariant": "repository co-location and Integration validation do not transfer Core ownership",
            "side_effects": {"index_changed": False, "commit_created": False, "push_performed": False},
        }
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument(
        "--baseline-plan",
        type=Path,
        help="require the staged index to exactly match a generated Core baseline plan",
    )
    parser.add_argument("--format", choices=("text", "json"), default="text")
    args = parser.parse_args()

    payload = verify_core_commit_scope(args.root, baseline_plan=args.baseline_plan)
    report = payload["core_commit_scope"]
    if args.format == "json":
        json.dump(payload, sys.stdout, ensure_ascii=False, indent=2)
        sys.stdout.write("\n")
    elif report["state"] == "passed":
        print(f"[PASS] Core commit scope verified: {report['staged_count']} staged paths")
    elif report["state"] == "pending":
        print("[PENDING] No staged Core commit scope to verify", file=sys.stderr)
    else:
        for item in report.get("forbidden_paths", ()):
            print(
                f"[FAIL] Core commit must not include {item['path']} (matches {item['pattern']})",
                file=sys.stderr,
            )
        plan = report.get("baseline_plan") or {}
        if plan and not plan.get("exact_staged_plan_match", False):
            print(
                "[FAIL] Staged index does not exactly match the generated Core baseline plan",
                file=sys.stderr,
            )
        if report.get("error") and not report.get("forbidden_paths"):
            print(f"[FAIL] {report['error']}", file=sys.stderr)

    raise SystemExit(0 if report["state"] == "passed" else 2 if report["state"] == "pending" else 1)


if __name__ == "__main__":
    main()
